<a href="https://colab.research.google.com/github/chrisbouton/MachineLearningMines/blob/main/Bouton_1b_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## CSCI 470 Activities and Case Studies

1. For all activities, you are allowed to collaborate with a partner. 
1. For case studies, you should work individually and are **not** allowed to collaborate.

By filling out this notebook and submitting it, you acknowledge that you are aware of the above policies and are agreeing to comply with them.

Some considerations with regard to how these notebooks will be graded:

1. Cells in which "# YOUR CODE HERE" is found are the cells where your graded code should be written.
2. In order to test out or debug your code you may also create notebook cells or edit existing notebook cells other than "# YOUR CODE HERE". We actually highly recommend you do so to gain a better understanding of what is happening. However, during grading, **these changes are ignored**. 
2. You must ensure that all your code for the particular task is available in the cells that say "# YOUR CODE HERE"
3. Every cell that says "# YOUR CODE HERE" is followed by a "raise NotImplementedError". You need to remove that line. During grading, if an error occurs then you will not receive points for your work in that section.
4. If your code passes the "assert" statements, then no output will result. If your code fails the "assert" statements, you will get an "AssertionError". Getting an assertion error means you will not receive points for that particular task.
5. If you edit the "assert" statements to make your code pass, they will still fail when they are graded since the "assert" statements will revert to the original. Make sure you don't edit the assert statements.
6. We may sometimes have "hidden" tests for grading. This means that passing the visible "assert" statements is not sufficient. The "assert" statements are there as a guide but you need to make sure you understand what you're required to do and ensure that you are doing it correctly. Passing the visible tests is necessary but not sufficient to get the grade for that cell.
7. When you are asked to define a function, make sure you **don't** use any variables outside of the parameters passed to the function. You can think of the parameters being passed to the function as a hint. Make sure you're using all of those variables.
8. Finally, **make sure you run "Kernel > Restart and Run All"** and pass all the asserts before submitting. If you don't restart the kernel, there may be some code that you ran and deleted that is still being used and that was why your asserts were passing.

## CSCI 470 Activities and Case Studies

1. For all activities, you are allowed to collaborate with a partner. 
1. For case studies, you should work individually and are **not** allowed to collaborate.

By filling out this notebook and submitting it, you acknowledge that you are aware of the above policies and are agreeing to comply with them.

# Optimization & Linear Algebra Review

In this exercise we will focus on the two main topics we covered in the lecture.

## Linear Algebra

In the lecture, with regards to Linear Algebra, we covered:

- some notation that we use for linear algebra
- special kinds of matrices
- matrix properties and operations
- norm definitions

Now let's practice some of these. 

In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
plt.style.use("ggplot")

In numpy we can create a vector or matrix or tensor using the [`np.array`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html) object.

An `np.array` stores data sequentially in computer memory (as opposed to randomly scattering data throughout computer memory) allowing them to take advantage of [spatial locality](https://en.wikipedia.org/wiki/Locality_of_reference). **Because of spatial locality, iterating through an `np.array` is much faster than iterating through a default Python array.**

In [2]:
vector = np.array([1,2,3])
print(vector)
print(f"The shape of our vector is {vector.shape}")

[1 2 3]
The shape of our vector is (3,)


In [3]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])
print(matrix)
print(f"The shape of our matrix is {matrix.shape}")

[[1 2 3]
 [4 5 6]]
The shape of our matrix is (2, 3)


In [4]:
tensor = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(tensor)
print(f"The shape of our tensor is {tensor.shape}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
The shape of our tensor is (2, 2, 3)


### Products

Let's try out some products now and check how they work. By default, numpy would do element wise multiplication if we use the `*` operator. Instead, we can use the [`@`](https://docs.python.org/3/library/operator.html#mapping-operators-to-functions) operator. (This is valid as of Python 3.5, otherwise you can use [`np.matmul`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html)).

Let's start by making some vectors and matrices. 

In [5]:
x = np.array([[1,2,3]]) # a row vector
y = np.array([[4],[5],[6]]) # a column vector

In [6]:
print(x)

[[1 2 3]]


In [7]:
print(y)

[[4]
 [5]
 [6]]


We can determine an array's dimensions by calling [`.shape`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html).

In [8]:
x.shape, y.shape

((1, 3), (3, 1))

Now let's try multiplying the two vectors to get their inner product. We'll also verify the result by manually calculating it.

In [9]:
x @ y, 1 * 4 + 2 * 5 + 3 * 6

(array([[32]]), 32)

Now let's look at how transpose works. With numpy, you can access the transpose of a `np.array` by calling its [`.T`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html) method or using [`np.transpose()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html). For simplicity, we will use `.T`.

In [10]:
print(x)
print(x.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [11]:
x.shape, x.T.shape

((1, 3), (3, 1))

The transpose of a matrix is still a matrix. Therefore, two transposed matrices can still be multiplied together as long as their inner dimensions align.

In [12]:
x.T.shape, y.T.shape

((3, 1), (1, 3))

In [13]:
z = x.T @ y.T
z

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

The resulting shape of a product matrix multiplication are the outside dimensions of the original matrices

In [14]:
z.shape

(3, 3)

In this next cell we can see that if the shapes of two different matrices do not align, the product will fail.

In [15]:
try:
    x.T @ y
except Exception as e:
    print(e)
    
try:
    x @ y.T
except Exception as e:
    print(e)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)


Squeezing can be used to get rid of any unused dimensions (ie. dimensions whose shape = 1). This ensures a variable can be treated as a vector instead of a matrix with 1 row.

For more information, check out the documentation for [`.squeeze`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.squeeze.html).

In [16]:
x, x.squeeze()

(array([[1, 2, 3]]), array([1, 2, 3]))

In [17]:
x.shape, x.squeeze().shape

((1, 3), (3,))

Notice nothing happens to Z because it does not contain any unused dimensions

In [18]:
z.squeeze()

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

When it is necessary to forcibly collapse a matrix into a single dimension, the `flatten` function can be used instead of `squeeze`

In [19]:
# For `x`, flatten works the same as squeeze. They both remove the unused dimension
x.flatten()

array([1, 2, 3])

In [20]:
# For `z`, flatten forces all values to be fit into a single dimension
z.flatten()

array([ 4,  5,  6,  8, 10, 12, 12, 15, 18])

NumPy implements many functions that are also built into Python.

When working with NumPy objects, both functions will work but it is always best to favor the NumPy implementations because they are much faster.

A list of NumPy functions can be found [here](https://numpy.org/doc/stable/reference/routines.math.html)

Check out how much faster the `np.sum` function is compared to Python's default `sum` function

In [21]:
testing_vector = np.array(range(100))
testing_vector_sum = np.sum(testing_vector)

In [22]:
%%timeit
assert sum(testing_vector) == testing_vector_sum

13.2 µs ± 3.11 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
%%timeit
assert np.sum(testing_vector) == testing_vector_sum

4.21 µs ± 46.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Now let's move on to some exercises.

In [24]:
X = np.array([
    [1, 2],
    [3, 4]
])
Y = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
X.shape, Y.shape

((2, 2), (2, 3))

In [25]:
# Calculate the product of X and Y and save it to the variable `out`
# YOUR CODE HERE
out = X @ Y

print(out)

[[ 9 12 15]
 [19 26 33]]


In [26]:
assert out.shape == (2,3)
assert out[0,0] == 1 * 1 + 2 * 4
assert out[1,1] == 3 * 2 + 4 * 5

In [27]:
print(f"The output shape of XY should be {X.shape[0]}, {Y.shape[1]}")
print(f"It is in fact, {out.shape} ")

The output shape of XY should be 2, 3
It is in fact, (2, 3) 


### Norms

Now let's calculate the norms that we discussed in the lecture.

#### Vector Norms

First, let's calculate the $\ell_1$ norm. We can calculate norms manually or using numpy's [`linalg.norm`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html) method.

In [28]:
ell_1_of_x = np.linalg.norm(x.squeeze(), 1)
sum_of_abs_of_x = np.abs(x).sum() 
print(ell_1_of_x, sum_of_abs_of_x)

6.0 6


Now calculate the $\ell_2$ norm of $\mathbf{x}$, once using the norm function and compare it to calculating it manually. Check the shape of $\mathbf{x}$ to make sure it is a vector. (You might need to use `.squeeze()`). 

In [29]:
#

# Use the norm function to calculate ell_2_of_x 
# Manually calculate the norm and save to manual_ell_2_of_x
print(X.shape)
# YOUR CODE HERE
ell_2_of_x = np.linalg.norm(X.squeeze(),2)
manual_ell_2_of_x = np.sqrt(np.square(X.squeeze()).sum())


ell_2_of_x = round(ell_2_of_x,1)
manual_ell_2_of_x = round(manual_ell_2_of_x,1)
#raise NotImplementedError()
print(ell_2_of_x)
print(manual_ell_2_of_x)

(2, 2)
5.5
5.5


In [30]:
assert ell_2_of_x == manual_ell_2_of_x

#### Matrix Norms

Test the multiple definitions of the Frobenius norm.

In [31]:
# Here we calculate the Frobenius norm manually
row_norms = []
for row in X:
    # Take norm of row and add it to our list of row norms
    row_norms.append(np.linalg.norm(row.flatten(), 2))
# Take norm of all row norms
manual_norm_calculation = np.linalg.norm(row_norms)
print(manual_norm_calculation)

5.477225575051661


In [32]:
# Here, we use matrix operations
linalg_norm_calculation = np.sum(X**2)**0.5
print(linalg_norm_calculation)

5.477225575051661


In [33]:
# We can also call np.linalg.norm directly
np_norm_calculation = np.linalg.norm(X)
print(np_norm_calculation)

5.477225575051661


In [34]:
assert manual_norm_calculation == np_norm_calculation == linalg_norm_calculation

The trace of a matrix is the sum of its diagonal.

With numpy we can calculate the trace of a matrix using [`np.trace`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.trace.html).

In [35]:
print(X)
np.diag(X).sum(), np.trace(X)

[[1 2]
 [3 4]]


(5, 5)

With trace, we can calculate the Frobenius norm a fourth way using the following equation (assuming A contains all real numbers):

$$||A_{m,n}||_F=\sqrt{\sum_{i=1}^m\sum_{j=1}^n|a_{ij}|^2}=\sqrt{Tr(A^{T}A)}$$

In [36]:
trace_norm_calculation = np.trace(X @ X.T)**0.5

In [37]:
assert manual_norm_calculation == np_norm_calculation == linalg_norm_calculation == trace_norm_calculation

### Special Matrices

Here we'll investigate the identity matrix, diagonal matrices, and symmetric matrices.

You can create an identity matrix using [`np.eye`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html)

In [38]:
five_identity = np.eye(5)
five_identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

[`np.diag`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html) is used to either create a diagonal matrix or extract the diagonal of an existing matrix.

In [39]:
D = np.diag([1,2,3,4,5])
D

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [40]:
np.diag(five_identity)

array([1., 1., 1., 1., 1.])

We can check if a matrix is Symmetric by using [`np.all`](https://numpy.org/doc/stable/reference/generated/numpy.all.html) to check if it is equivalent to its transpose.

Is a diagonal matrix symmetric?

In [41]:
print(f"It is {np.all(D == D.T)} that D is a symmetric matrix")

It is True that D is a symmetric matrix


In [42]:
print(f"It is {np.all(X == X.T)} that X is a symmetric matrix")

It is False that X is a symmetric matrix


We can calculate the rank of a matrix using [`np.linalg.matrix_rank`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.matrix_rank.html).

In [43]:
np.linalg.matrix_rank(X)

2

In [44]:
np.linalg.matrix_rank(five_identity)

5

In [45]:
np.linalg.matrix_rank(np.array([
    [1, 2, 3],
    [2, 4, 6]
]))

1

In [46]:
np.linalg.matrix_rank(np.array([
    [1, 2, 4],
    [2, 4, 6]
]))

2

Ensure these numbers make sense to you based on your conception of rank.

## Decomposition

Now let's look at decomposing a matrix into multiple matrices. We have two main methods of doing so. Singular Value Decomposition works on all matrices and eigenvalue decomposition works on square matrices.

We can use [`linalg.svd`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.svd.html) to calculate the SVD of a matrix and [`linalg.eig`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.eig.html) to form the eigenvalue decomposition of a square matrix

In [47]:
U, Sigma, VT = np.linalg.svd(Y)
V = VT.T
print(U)
print(V)
print(Sigma)
U@U.T, U.T @ U, V@V.T, V.T @ V

[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
[[-0.42866713  0.80596391  0.40824829]
 [-0.56630692  0.11238241 -0.81649658]
 [-0.7039467  -0.58119908  0.40824829]]
[9.508032   0.77286964]


(array([[ 1.00000000e+00, -8.49433239e-18],
        [-8.49433239e-18,  1.00000000e+00]]),
 array([[ 1.00000000e+00, -8.49433239e-18],
        [-8.49433239e-18,  1.00000000e+00]]),
 array([[1.00000000e+00, 1.16059657e-16, 9.83171390e-17],
        [1.16059657e-16, 1.00000000e+00, 4.58633852e-19],
        [9.83171390e-17, 4.58633852e-19, 1.00000000e+00]]),
 array([[ 1.00000000e+00,  4.13108370e-17,  2.21870637e-17],
        [ 4.13108370e-17,  1.00000000e+00, -1.77008767e-16],
        [ 2.21870637e-17, -1.77008767e-16,  1.00000000e+00]]))

Check the orthogonality of the resulting matrices.

In [48]:
U@U.T, U.T @ U, V@V.T, V.T @ V

(array([[ 1.00000000e+00, -8.49433239e-18],
        [-8.49433239e-18,  1.00000000e+00]]),
 array([[ 1.00000000e+00, -8.49433239e-18],
        [-8.49433239e-18,  1.00000000e+00]]),
 array([[1.00000000e+00, 1.16059657e-16, 9.83171390e-17],
        [1.16059657e-16, 1.00000000e+00, 4.58633852e-19],
        [9.83171390e-17, 4.58633852e-19, 1.00000000e+00]]),
 array([[ 1.00000000e+00,  4.13108370e-17,  2.21870637e-17],
        [ 4.13108370e-17,  1.00000000e+00, -1.77008767e-16],
        [ 2.21870637e-17, -1.77008767e-16,  1.00000000e+00]]))

Let's create a symmetric matrix $\mathbf{S}$ to verify SVD's equivalence to eigenvalue decomposition when the matrix is symmetric.

In [49]:
S = np.array([
    [1, 7, 6],
    [7, 3, 5],
    [6, 5, 9]
])

In [50]:
U, Sigma, VT = np.linalg.svd(S)
V = VT.T
print(U)
print(V)
print(Sigma)

[[-0.49359494  0.79161173 -0.36015956]
 [-0.5071001  -0.5984062  -0.62028985]
 [-0.70655044 -0.12353498  0.69679666]]
[[-0.49359494 -0.79161173 -0.36015956]
 [-0.5071001   0.5984062  -0.62028985]
 [-0.70655044  0.12353498  0.69679666]]
[16.78015247  5.22786793  1.44771546]


In [51]:
# Calculate the eigenvalues and eigenvectors of S (hint: using one of the functions referenced above) 
#   and save them to eig_vals and eig_vecs respectively.
# YOUR CODE HERE
eig_vals = Sigma
eig_vecs = S.T@S
print(eig_vals.shape)
print(eig_vecs.shape)

(3,)
(3, 3)


In [52]:
assert eig_vals.shape == (3,)
assert eig_vecs.shape == (3,3)

Verify some properties of eigenvalues for square matrices.

In [53]:
np.linalg.eigvals(S.T @ S), np.linalg.eigvals(S @ S.T), np.linalg.eigvals(S) ** 2

(array([281.57351691,  27.33060305,   2.09588004]),
 array([281.57351691,  27.33060305,   2.09588004]),
 array([281.57351691,  27.33060305,   2.09588004]))

Congratualtions, you made it!

If after these exercises you're realizing that your knowledge of linear algebra is a little rusty, consider diving down a YouTube rabbit hole starting with [this excellent video](https://www.youtube.com/watch?v=PFDu9oVAE-g). It's a lot more fun to admire the subtle beauty of math when a stressful due date isn't looming.

With that being said, we won't spend too much more time on Linear Algebra in this class.

But, gaining an intuition for it promotes a pretty cool conception for thinking about multi-dimensional space. The notation is impressively succinct and it will become very relevant in the later math classes on the CSCI + Data Science track (*cough* Multivariate Analysis *cough*).

## Feedback

In [54]:
def feedback():
    """Provide feedback on the contents of this exercise
    
    Returns:
        string
    """
    # YOUR CODE HERE
    return "Not bad!"