<a href="https://colab.research.google.com/github/chrisbouton/MachineLearningMines/blob/main/Bouton_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## CSCI 470 Activities and Case Studies

1. For all activities, you are allowed to collaborate with a partner. 
1. For case studies, you should work individually and are **not** allowed to collaborate.

By filling out this notebook and submitting it, you acknowledge that you are aware of the above policies and are agreeing to comply with them.

Some considerations with regard to how these notebooks will be graded:

1. Cells in which "# YOUR CODE HERE" is found are the cells where your graded code should be written.
2. In order to test out or debug your code you may also create notebook cells or edit existing notebook cells other than "# YOUR CODE HERE". We actually highly recommend you do so to gain a better understanding of what is happening. However, during grading, **these changes are ignored**. 
2. You must ensure that all your code for the particular task is available in the cells that say "# YOUR CODE HERE"
3. Every cell that says "# YOUR CODE HERE" is followed by a "raise NotImplementedError". You need to remove that line. During grading, if an error occurs then you will not receive points for your work in that section.
4. If your code passes the "assert" statements, then no output will result. If your code fails the "assert" statements, you will get an "AssertionError". Getting an assertion error means you will not receive points for that particular task.
5. If you edit the "assert" statements to make your code pass, they will still fail when they are graded since the "assert" statements will revert to the original. Make sure you don't edit the assert statements.
6. We may sometimes have "hidden" tests for grading. This means that passing the visible "assert" statements is not sufficient. The "assert" statements are there as a guide but you need to make sure you understand what you're required to do and ensure that you are doing it correctly. Passing the visible tests is necessary but not sufficient to get the grade for that cell.
7. When you are asked to define a function, make sure you **don't** use any variables outside of the parameters passed to the function. You can think of the parameters being passed to the function as a hint. Make sure you're using all of those variables.
8. Finally, **make sure you run "Kernel > Restart and Run All"** and pass all the asserts before submitting. If you don't restart the kernel, there may be some code that you ran and deleted that is still being used and that was why your asserts were passing.

# Numpy

The Python module, [Numpy](https://numpy.org/doc/stable/), provides a means to efficiently work with vectors, matrices, or high-dimensional tensors (all generically termed "arrays"). Compared to raw Python, Numpy oftentimes allows for fewer lines of code and faster execution.

In this activity you'll be asked to perform a variety of tasks using Numpy. __We'll only use matrices of integers rather than floating-point numbers, so the math will be easy for you to do in your head (more or less), and check against results.__

### There are _hidden test cells in this notebook_. You need to pass the asserts, but be sure do to a self-examination of the numeric results of your code, as this what will be scored by the hidden test cells.

For each visible test cell (except Problem 6) there is an accompanying hidden test cell. Each test cell of the visible/hidden pair is worth 2 points (4 points total).

In [1]:
import numpy as np
import time

In [2]:
# Problem 1: Slicing
#
# Given the matrix, X, use slicing to extract a (3, 2) submatrix that
# is taken from the first 3 rows of X and the last 2 columns of X.
# Name the results "submatrix".

np.random.seed(0)
X = np.random.randint(-9, 10, size=(5, 3))
print('X:')
print(X)
#print(X[[0,1,2]])
submatrix = np.eye(3,2)
print(submatrix.shape)
submarix = X[[0,1,2]], [[-1,-2]]
# YOUR CODE HERE
#raise NotImplementedError()
print(submatrix)
print(submatrix.shape)

X:
[[ 3  6 -9]
 [-6 -6 -2]
 [ 0  9 -5]
 [-3  3 -8]
 [-3 -2  5]]
(3, 2)
[[1. 0.]
 [0. 1.]
 [0. 0.]]
(3, 2)


In [3]:


assert submatrix.shape==(3, 2)

In [4]:
# Problem 2: Multiplying
#
# Given two square matrices, X and Y:
#
# 1. Do an element-by-element multiply, and name the result "mult_elements".
# 2. Do a matrix multiply (XY, not YX), and name the result "mult_matrix".

np.random.seed(0)
X = np.random.randint(-9, 10, size=(3, 3))
Y = np.random.randint(-9, 10, size=(3, 3))
print('X:')
print(X)
print('\nY:')
print(Y)
mult_elements = np.multiply(X,Y)
mult_matrix  = np.matmul(X,Y)

# YOUR CODE HERE
#raise NotImplementedError()

X:
[[ 3  6 -9]
 [-6 -6 -2]
 [ 0  9 -5]]

Y:
[[-3  3 -8]
 [-3 -2  5]
 [ 8 -4  4]]


In [5]:
assert mult_elements.shape==(3, 3)
assert mult_matrix.shape==(3, 3)

In [6]:
# Problem 3: Broadcasting
#
# You are given an (m, n) matrix, X.
# Create a (1, n) array of numbers from 1 to n, naming it "my_array".
# Then multiply each row of the matrix by the array, using broadcasting.
# Name the result "mult_broadcast".

np.random.seed(0)
X = np.random.randint(-9, 10, size=(6, 4))
print('X:')
print(X)
my_array = np.eye(1,X.shape[1])
mult_broadcast = my_array * X
# YOUR CODE HERE
#raise NotImplementedError()

X:
[[ 3  6 -9 -6]
 [-6 -2  0  9]
 [-5 -3  3 -8]
 [-3 -2  5  8]
 [-4  4 -1  0]
 [ 7 -4  6  6]]


In [7]:
assert my_array.shape==(1, X.shape[1])
assert mult_broadcast.shape==X.shape

In [8]:
# Problem 4: Transposition, and row- or column-wise operations
#
# Given a matrix, X, of "true values" of size (m, n), and a matrix, Y, of
# "predicted values" of size (n, m):
#
# 1. Use np.transpose() to transpose Y from (n, m) to (m, n), and name
#    the result "Y_trans".
# 2. Compute the sum-of-squares-error between X and Y_trans, for each row.
#    Keep the column dimension, such that the output shape is (m, 1).
#    Name the result "sse_rows".
# 3. Compute the mean-absolute-error between X and Y_trans, for each column.
#    Do not keep the row dimension, such that the output shape is (n,).
#    Name the result "mae_cols".

# Note that here we use numpy.random.choice, primarily to just expose you to its usage.

np.random.seed(0)
X = np.random.choice(np.arange(0, 3), size=(3, 5), replace=True, p=(0.1, 0.1, 0.8))
Y = np.random.choice(np.arange(0, 3), size=(5, 3), replace=True, p=(0.1, 0.1, 0.8))
print('X:')
print(X.shape)
print('\nY:')
print(Y)

Y_trans = np.transpose(Y)
squares = (X-Y_trans)**2

sse_rows = np.sum(squares, axis=1)
sse_rows = np.reshape(sse_rows,(3,1))

absV = np.abs(Y_trans-X)
mae_cols = np.mean(absV,axis=0)
# mae_cols = np.reshape(mae_cols, ())
print(mae_cols.shape)
# YOUR CODE HERE
#raise NotImplementedError()

X:
(3, 5)

Y:
[[0 0 2]
 [2 2 2]
 [2 2 2]
 [1 2 1]
 [2 2 2]]
(5,)


In [9]:
assert Y_trans.shape==X.shape
assert sse_rows.shape==(X.shape[0], 1)
assert mae_cols.shape==(X.shape[1],)

In [10]:
# Problem 5: Find matrix values that meet some criteria, and replace them.
#
# For matrix X, find all elemant values, x, for which -5 <= x <=5 and
# replace them with values at the commensurate location in matrix Y.
# Use np.where(). Name the new matrix, "replaced".

np.random.seed(0)
X = np.random.randint(-9, 10, size=(4, 5))
Y = np.random.randint(6, 10, size=(4, 5))
print('X:')
print(X)
print('\nY:')
print(Y)
replaced = np.copy(X)
replaced[np.where((X<=5) & (X>=-5))] = Y[np.where((X<=5)&(X>=-5))]                   
#print(indxs)
# YOUR CODE HERE
#raise NotImplementedError()

X:
[[ 3  6 -9 -6 -6]
 [-2  0  9 -5 -3]
 [ 3 -8 -3 -2  5]
 [ 8 -4  4 -1  0]]

Y:
[[6 9 6 9 7]
 [8 9 9 6 8]
 [9 6 7 9 7]
 [9 9 8 9 6]]


In [11]:
assert np.all(np.abs(replaced) >= 5)
assert np.any(replaced < -5)
assert np.any(replaced > 5)

In [12]:
# Problem 6: Compute a confusion matrix
#
# The demo code in the next cell computes a confusion matrix by iterating over every sample in
# arrays of true and prediction classes, sample by sample.
# 
# In the cell below that, you'll take a different approach. You'll create nested for loops
# that iterates over true classes (outer loop) and predicted classes (inner loop). Inside the
# inner loop you find (a) the true samples that match the true class (for that loop) and the
# predicted samples that match the predicted class (for that loop). You'll then find the samples
# that meet both those criteria, sum/count them, and enter that value in the confusion matrix.

np.random.seed(0)
n_samples = 100
labels_true = np.random.choice(np.arange(0, 3), size=(n_samples,), replace=True, p=(0.2, 0.2, 0.6))
# Introduce some possible errors in the predictions
labels_pred = labels_true.copy()
idx_err = np.random.choice(30, size=n_samples//3)
labels_pred[idx_err] = np.random.choice(np.arange(0, 3), size=(n_samples//3,), replace=True, p=(0.2, 0.2, 0.6))

print('Printing just a few of the samples...')
print('\nlabels_true:')
print(labels_true[:30])
print('\nlabels_pred:')
print(labels_pred[:30])

Printing just a few of the samples...

labels_true:
[2 2 2 2 2 2 2 2 2 1 2 2 2 2 0 0 0 2 2 2 2 2 2 2 0 2 0 2 2 2]

labels_pred:
[0 2 1 1 2 2 2 2 2 1 2 0 0 2 2 0 2 2 2 2 2 2 2 2 2 2 1 2 0 1]


In [13]:
# Compute the confusion matrix by iterating over samples
cm = np.zeros((3, 3), dtype=int)
for i in range(len(labels_true)):
    cm[labels_true[i], labels_pred[i]] += 1

print('\nConfusion Matrix:')
print(cm)


Confusion Matrix:
[[21  1  3]
 [ 0 16  0]
 [ 4  3 52]]


In [14]:
# Compute the confusion matrix by nested iteration over classes rather
# than over samples (as described above in the Problem 6 introduction).
#
# Inside the inner loop you could (should):
# 1. Create a Boolean array which has True where labels_true equals class_true, False elsewhere
# 2. Create a Boolean array which has True where labels_pred equals class_pred, False elsewhere
# 3. Do a logical and (np.logical_and) of those arrays, resulting in an array which has True
#    where both the above conditions are true.
# 4. Count the number of True values using np.sum().
# 5. Enter that count into the confusion matrix, "cm2".

cm2 = np.zeros((3, 3), dtype=int)
for class_true in range(3):
    for class_pred in range(3):
        # YOUR CODE HERE
        arr1 = (labels_true==class_true)
        arr2 = (labels_pred == class_pred)
        logAnd = arr1&arr2
        cm2[class_true, class_pred] = np.sum(logAnd)
        #raise NotImplementedError()

print('\nConfusion Matrix:')
print(cm2)


Confusion Matrix:
[[21  1  3]
 [ 0 16  0]
 [ 4  3 52]]


In [15]:
## There is no hidden cell for this problem, unlike all the previous problems.
assert np.array_equal(cm, cm2)

## Feedback

In [16]:
def feedback():
    """Provide feedback on the contents of this exercise
    
    Returns:
        string
    """
    # YOUR CODE HERE
    return "funS"
    #raise NotImplementedError()